/*  =========================================================================
    agent-th - generated layer of public API

    Code in this repository is part of Eaton Intelligent Power Controller SW suite 
                                                                                   
    Copyright © 2015-2016 Eaton. This software is confidential and licensed under 
    Eaton Proprietary License (EPL or EULA).                                       
                                                                                   
    This software is not authorized to be used, duplicated or disclosed to anyone  
    without the prior written permission of Eaton.                                 
                                                                                   
    Limitations, restrictions and exclusions of the Eaton applicable standard terms
    and conditions, such as its EPL and EULA, apply.                               

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef AGENT_TH_LIBRARY_H_INCLUDED
#define AGENT_TH_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <malamute.h>
#include <biosproto.h>

//  AGENT_TH version macros for compile-time API detection
#define AGENT_TH_VERSION_MAJOR 0
#define AGENT_TH_VERSION_MINOR 0
#define AGENT_TH_VERSION_PATCH 0

#define AGENT_TH_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define AGENT_TH_VERSION \
    AGENT_TH_MAKE_VERSION(AGENT_TH_VERSION_MAJOR, AGENT_TH_VERSION_MINOR, AGENT_TH_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined AGENT_TH_STATIC
#       define AGENT_TH_EXPORT
#   elif defined AGENT_TH_EXPORTS
#       define AGENT_TH_EXPORT __declspec(dllexport)
#   else
#       define AGENT_TH_EXPORT __declspec(dllimport)
#   endif
#else
#   define AGENT_TH_EXPORT
#endif

//  Project has no stable classes, so we build the draft API
#undef  AGENT_TH_BUILD_DRAFT_API
#define AGENT_TH_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases


//  Public classes, each with its own header file

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
