/*  =========================================================================
    agent-th - AGENT-TH wrapper

    Copyright (C) 2014 - 2015 Eaton

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef TH_LIBRARY_H_INCLUDED
#define TH_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <malamute.h>
#include <biosproto.h>

//  AGENT-TH version macros for compile-time API detection

#define AGENT_TH_VERSION_MAJOR 0
#define AGENT_TH_VERSION_MINOR 0
#define AGENT_TH_VERSION_PATCH 0

#define AGENT_TH_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define AGENT_TH_VERSION \
    AGENT_TH_MAKE_VERSION(AGENT_TH_VERSION_MAJOR, AGENT_TH_VERSION_MINOR, AGENT_TH_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined LIBTH_STATIC
#       define TH_EXPORT
#   elif defined LIBTH_EXPORTS
#       define TH_EXPORT __declspec(dllexport)
#   else
#       define TH_EXPORT __declspec(dllimport)
#   endif
#else
#   define TH_EXPORT
#endif

//  Opaque class structures to allow forward references
typedef struct _libth_t libth_t;
#define LIBTH_T_DEFINED


//  Public API classes
#include "libth.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
