/*  =========================================================================
    agent-th - AGENT-TH wrapper

    Code in this repository is part of Eaton Intelligent Power Controller SW suite                                                        
                                                                                                                                          
    Copyright © 2015-2016 Eaton. This software is confidential and licensed under
    Eaton Proprietary License (EPL or EULA).

    This software is not authorized to be used, duplicated or disclosed to anyone
    without the prior written permission of Eaton.

    Limitations, restrictions and exclusions of the Eaton applicable standard terms
    and conditions, such as its EPL and EULA, apply.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef TH_LIBRARY_H_INCLUDED
#define TH_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <malamute.h>
#include <bios/bios_agent.h>
#include <bios/agents.h>

//  AGENT-TH version macros for compile-time API detection

#define AGENT_TH_VERSION_MAJOR 0
#define AGENT_TH_VERSION_MINOR 0
#define AGENT_TH_VERSION_PATCH 0

#define AGENT_TH_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define AGENT_TH_VERSION \
    AGENT_TH_MAKE_VERSION(AGENT_TH_VERSION_MAJOR, AGENT_TH_VERSION_MINOR, AGENT_TH_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined LIBTH_STATIC
#       define TH_EXPORT
#   elif defined LIBTH_EXPORTS
#       define TH_EXPORT __declspec(dllexport)
#   else
#       define TH_EXPORT __declspec(dllimport)
#   endif
#else
#   define TH_EXPORT
#endif

//  Opaque class structures to allow forward references
typedef struct _libth_t libth_t;
#define LIBTH_T_DEFINED


//  Public API classes
#include "libth.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
