/*  =========================================================================
    agent_th_classes - private header file

    Code in this repository is part of Eaton Intelligent Power Controller SW suite 
                                                                                   
    Copyright © 2015-2016 Eaton. This software is confidential and licensed under 
    Eaton Proprietary License (EPL or EULA).                                       
                                                                                   
    This software is not authorized to be used, duplicated or disclosed to anyone  
    without the prior written permission of Eaton.                                 
                                                                                   
    Limitations, restrictions and exclusions of the Eaton applicable standard terms
    and conditions, such as its EPL and EULA, apply.                               
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef AGENT_TH_CLASSES_H_INCLUDED
#define AGENT_TH_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/agent_th.h"

//  Internal API
#include "logger.h"
#include "libth.h"

//  *** To avoid double-definitions, only define if building without draft ***
#ifndef AGENT_TH_BUILD_DRAFT_API

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
AGENT_TH_EXPORT void
    logger_test (bool verbose);

//  *** Draft method, defined for internal use only ***
//  Self test of this class.
AGENT_TH_EXPORT void
    libth_test (bool verbose);

#endif // AGENT_TH_BUILD_DRAFT_API

#endif
