/*  =========================================================================
    th_classes - private header file

    Code in this repository is part of Eaton Intelligent Power Controller SW suite                                                        
                                                                                                                                          
    Copyright © 2015-2016 Eaton. This software is confidential and licensed under
    Eaton Proprietary License (EPL or EULA).

    This software is not authorized to be used, duplicated or disclosed to anyone
    without the prior written permission of Eaton.

    Limitations, restrictions and exclusions of the Eaton applicable standard terms
    and conditions, such as its EPL and EULA, apply.
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef TH_CLASSES_H_INCLUDED
#define TH_CLASSES_H_INCLUDED

//  External API
#include "../include/agent_th.h"

//  Internal API

#endif
